name: test release
on:
  pull_request:
    branches: [ main ]

jobs:
  # mock job to show that it runs
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
  lint:
    if:  startsWith(github.head_ref, 'release-please-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  test:
    runs-on: ubuntu-latest
    container: riedmiki/gromacs-plumed-python:2021
    needs: lint
    steps:
      - uses  : actions/checkout@v3
      - name: run tox
        run: tox
      - name: zip coverage report
        if: ${{ !cancelled() }}
        run: zip -r htmlcov.zip htmlcov || true
      - uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: coverage artifact
          path: htmlcov.zip

          
